-- GC-T014 / #721: expand the seeded NIST SP 800-30 Rev. 1 methodology profile
-- with the full Rev. 1 decomposition (threat sources, threat events,
-- vulnerabilities, predisposing conditions, threat-source relevance, multi-
-- dimensional likelihood, impact level, assessment timeframe). seedIfMissing()
-- in MethodologyProfileService only handles the missing-row path; existing
-- rows in production / dev / test require this in-place UPDATE so the schema
-- vocabulary used to validate NIST inputs is consistent with the new analysis
-- endpoint (/api/v1/analysis/grc/nist-sp-800-30) and the NistAssessmentService
-- domain model.

UPDATE methodology_profile
SET
    description = 'NIST SP 800-30 Rev. 1 qualitative risk assessment using the full Rev. 1 decomposition (threat sources, threat events, vulnerabilities, predisposing conditions, likelihoods, impact) with the 5x5 risk matrix (Table I-2).',
    input_schema = '{"type":"object","description":"NIST SP 800-30 Rev. 1 assessment inputs (full Rev. 1 decomposition per GC-T014)","properties":{"threat_source":{"type":"object","description":"Threat source per NIST SP 800-30 Rev. 1 Appendix D","properties":{"id":{"type":"string"},"name":{"type":"string"},"kind":{"type":"string","enum":["ADVERSARIAL","NON_ADVERSARIAL"]}}},"threat_event":{"type":"object","description":"Threat event per NIST SP 800-30 Rev. 1 Appendix E","properties":{"id":{"type":"string"},"description":{"type":"string"},"kind":{"type":"string","enum":["ADVERSARIAL","NON_ADVERSARIAL"]}}},"threat_event_kind":{"type":"string","enum":["ADVERSARIAL","NON_ADVERSARIAL"]},"threat_source_characteristics":{"type":"object","description":"Adversarial threat source attributes (NIST Table D-3..D-5); not applicable to non-adversarial events","properties":{"capability":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]},"intent":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]},"targeting":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]}}},"threat_source_relevance":{"type":"string","description":"Threat source relevance per NIST Table D-2","enum":["CONFIRMED","EXPECTED","ANTICIPATED","PREDICTED","POSSIBLE","NOT_APPLICABLE"]},"vulnerabilities":{"type":"array","description":"Vulnerabilities exposed to the threat event (NIST Appendix F)","items":{"type":"object","properties":{"id":{"type":"string"},"description":{"type":"string"},"severity":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]},"predisposing_condition_ids":{"type":"array","items":{"type":"string"}}}}},"predisposing_conditions":{"type":"array","description":"Predisposing conditions affecting exploitation (NIST Appendix F)","items":{"type":"object","properties":{"id":{"type":"string"},"description":{"type":"string"},"pervasiveness":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]}}}},"likelihood_initiation":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]},"likelihood_adverse_impact":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]},"likelihood_overall":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]},"impact_level":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]},"assessment_timeframe":{"type":"object","properties":{"from":{"type":"string","format":"date"},"to":{"type":"string","format":"date"}}}},"required":["impact_level"],"semantics":{"scale":"ordinal","levels":5,"level_labels":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"],"score_range":{"min":1,"max":5},"units":"qualitative ordinal levels","adversarial_branch_fields":["threat_source_characteristics"],"non_adversarial_branch_fields":[]}}',
    output_schema = '{"type":"object","description":"NIST SP 800-30 Rev. 1 risk determination outputs (methodology-attributed per GC-L007 result contract)","properties":{"overall_likelihood":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]},"impact_level":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]},"risk_level":{"type":"string","enum":["VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH"]},"matrix_cell":{"type":"string","description":"e.g. L3-I4"},"derivation":{"type":"string","description":"analyst-supplied or derived per Table G-5"}},"required":["risk_level"],"semantics":{"scale":"ordinal","units":"qualitative ordinal levels","derivation_method":"nist-sp800-30-rev1-5x5-matrix-v1","matrix_conversion_rule":"overall_likelihood × impact_level → risk_level per NIST SP 800-30 Rev. 1 Table I-2","no_numeric_score":"NIST ordinal bands must not be normalized into a cross-methodology numeric score without an explicit method label and conversion rule"}}'
WHERE profile_key = 'NIST_SP800_30_R1';
