-- GC-GRC-016 (#1129): Envers audit shadow for grc_assessment_run. project_id is
-- intentionally absent because the JPA association is @NotAudited; all bounded
-- run/review/graph-effect metadata remains audited.
CREATE TABLE grc_assessment_run_audit (
    id                        UUID         NOT NULL,
    rev                       INTEGER      NOT NULL REFERENCES revinfo(rev),
    revtype                   SMALLINT     NOT NULL,
    mode                      VARCHAR(30),
    scope_type                VARCHAR(40),
    scope_values              TEXT,
    commit_sha                VARCHAR(64),
    base_commit_sha           VARCHAR(64),
    languages                 TEXT,
    surfaces                  TEXT,
    declared_boundaries       TEXT,
    threat_pack_id            VARCHAR(200),
    threat_pack_version       VARCHAR(100),
    review_policy             VARCHAR(30),
    review_decision           VARCHAR(30),
    state                     VARCHAR(30),
    reviewed_by               VARCHAR(200),
    reviewed_at               TIMESTAMPTZ,
    review_rationale          VARCHAR(2000),
    idempotency_key           VARCHAR(200),
    partition_count           INTEGER,
    deduped_partition_count   INTEGER,
    duplicate_partition_count INTEGER,
    partitions                TEXT,
    merge_summary             TEXT,
    graph_effects             TEXT,
    graph_effect_count        INTEGER,
    created_at                TIMESTAMPTZ,
    updated_at                TIMESTAMPTZ,
    PRIMARY KEY (id, rev)
);
