-- ADR-084 §5 / issue #1309: bind AGE graph snapshots to the Envers as-of spine.
--
-- source_revision records the Envers revision (revinfo.rev) that was visible to the
-- REPEATABLE_READ transaction that built this snapshot's projection — the revision
-- coordinate, not an authorization or a retention guarantee.
--
-- Nullable, no default: legacy snapshot rows published before this migration stay
-- explicitly unbound (NULL) rather than carry a fabricated coordinate, because a
-- materialization spans time and the revision visible at publication cannot be inferred
-- after the fact from published_at. No backfill.
--
-- No FK to revinfo(rev): AuditRetentionJob deletes revinfo rows past the retention
-- window, and a FK here would either block that cleanup or silently turn old snapshots
-- into retention pins. The column is bound as a plain JDBC parameter by
-- AgeGraphSnapshotRepository.insertSnapshot, not enforced referentially.
ALTER TABLE age_graph_snapshot ADD COLUMN source_revision INTEGER;
