package com.keplerops.groundcontrol.domain.graph.model;

public enum GraphEntityType {
    REQUIREMENT,
    OPERATIONAL_ASSET,
    OBSERVATION,
    RISK_SCENARIO,
    CONTROL,
    CONTROL_TEST,
    VERIFICATION_RESULT,
    THREAT_MODEL,
    FINDING,
    EVIDENCE_ARTIFACT,
    AUDIT,
    RISK_CONTROL_MAPPING,
    SCOPED_CONTROL_IMPLEMENTATION,
    DOCUMENT,
    RESEARCH_RUN,
    RESEARCH_ARTIFACT,
    RESEARCH_PROVENANCE_NODE,
    ARTIFACT_REFERENCE
}
